---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    driver_config:
      forward:
      - 8080:8080

suites:
  - name: default
    run_list:
      - recipe[test-class-jenkins::default]
    attributes:
